name: Test and Release
on:
  push:
    branches:
      - master

jobs:
  test-and-release:
    name: Run tests and release to npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn ci
      - name: Bundle
        run: yarn build
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn run semantic-release
      - name: Build Storybook
        run: yarn storybook:export
      - name: Deploy Storybook to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: storybook-static
